---
deployment:
  tasks:
    - export DEPLOYPATH=/home/campqvyh/portal.campaignersmiu.com
    - export ROOTPATH=/home/campqvyh/temp_
    - /bin/cp $DEPLOYPATH/classes/DB.php $ROOTPATH/classes_temp
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp $ROOTPATH/classes_temp/DB.php $DEPLOYPATH/classes

